# Generated by Django 5.0.2 on 2024-02-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatable',
            name='age',
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='office',
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='position',
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='salary',
        ),
        migrations.AddField(
            model_name='datatable',
            name='col1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datatable',
            name='col2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datatable',
            name='col3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datatable',
            name='col4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datatable',
            name='col5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
