# Generated by Django 5.0.2 on 2024-02-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_datatable_age_remove_datatable_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatable',
            old_name='col1',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='datatable',
            old_name='col2',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='datatable',
            old_name='col3',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='datatable',
            old_name='col4',
            new_name='engine',
        ),
        migrations.RenameField(
            model_name='datatable',
            old_name='col5',
            new_name='speed',
        ),
    ]
