# Generated by Django 5.0.2 on 2024-02-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comptable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comptable',
            name='eds_rvp_conversion',
        ),
        migrations.RemoveField(
            model_name='comptable',
            name='outscan_Performance',
        ),
    ]
