# Generated by Django 5.0.2 on 2024-02-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_comptable_eds_rvp_conversion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptable',
            old_name='eds',
            new_name='brokage',
        ),
        migrations.RenameField(
            model_name='comptable',
            old_name='eds_conversion',
            new_name='buy_or_sell',
        ),
        migrations.RenameField(
            model_name='comptable',
            old_name='fresh',
            new_name='closing_rate',
        ),
        migrations.RenameField(
            model_name='comptable',
            old_name='overall_conversion',
            new_name='gross_rate',
        ),
        migrations.RenameField(
            model_name='comptable',
            old_name='rvp',
            new_name='net_rate',
        ),
        migrations.RenameField(
            model_name='comptable',
            old_name='rvp_done',
            new_name='net_total',
        ),
        migrations.RenameField(
            model_name='comptable',
            old_name='service_center',
            new_name='order_number',
        ),
        migrations.AddField(
            model_name='comptable',
            name='order_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comptable',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comptable',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comptable',
            name='security_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comptable',
            name='trade_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comptable',
            name='trade_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
